services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: kiruhak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kiruhak
      POSTGRES_USER: kiruhak_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kiruhak_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiruhak_user -d kiruhak"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Основное приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiruhak_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://kiruhak_user:${POSTGRES_PASSWORD}@postgres:5432/kiruhak
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_CHANNEL_USERNAME: ${TELEGRAM_CHANNEL_USERNAME}
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL}
    ports:
      - "3015:3015"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kiruhak_network
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3015/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram бот
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: kiruhak_bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHANNEL_USERNAME: ${TELEGRAM_CHANNEL_USERNAME}
      API_URL: http://app:3015/api/auth/create-account
    depends_on:
      app:
        condition: service_healthy
    networks:
      - kiruhak_network
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://app:3015/api/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  kiruhak_network:
    driver: bridge
